
CREATE TABLE "DEV"."P_INFO_DETAIL" 
   (  "ID" VARCHAR2(36), 
  "P_ID" VARCHAR2(36), 
  "NAME" VARCHAR2(100), 
  "TYPE" VARCHAR2(100), 
  "UNIT" VARCHAR2(20), 
  "NUM" VARCHAR2(20), 
  "USE" VARCHAR2(100), 
  "GETDATE" VARCHAR2(50), 
  "REMARK" VARCHAR2(200), 
  "IS_DELETE" NUMBER(1) DEFAULT 0, 
  "CREATE_USER" VARCHAR2(50), 
  "CREATE_TIME" VARCHAR2(50), 
  "UPDATE_USER" VARCHAR2(50), 
  "UPDATE_TIME" VARCHAR2(50)
   ) ;
 
   COMMENT ON COLUMN "DEV"."P_INFO_DETAIL"."name" IS '物资名称';
 
   COMMENT ON COLUMN "DEV"."P_INFO_DETAIL"."type" IS '型号';
 
   COMMENT ON COLUMN "DEV"."P_INFO_DETAIL"."unit" IS '单位';
   
   COMMENT ON COLUMN "DEV"."P_INFO_DETAIL"."getdate" IS '到货时间';
   
   COMMENT ON COLUMN "DEV"."P_INFO_DETAIL"."use" IS '用途';
    
