create table P_INFO
(
  UUID        VARCHAR2(36),
  APPLY_ID    VARCHAR2(36),
  APPLY_NAME  VARCHAR2(50),
  APPLY_TIME  VARCHAR2(16),
  LEAD_F_VIEW VARCHAR2(200),
  LEAD_S_VIEW VARCHAR2(200),
  LEAD_T_VIEW VARCHAR2(200),
  REMARK      VARCHAR2(500),
  STATE       CHAR(1),
  IS_DELETE   NUMBER(1) default 0,
  CREATE_USER VARCHAR2(50),
  CREATE_TIME VARCHAR2(50),
  UPDATE_USER VARCHAR2(50),
  UPDATE_TIME VARCHAR2(50)
)
 
   COMMENT ON COLUMN "DEV"."P_INFO"."LEAD_F_VIEW" IS '第一审核人意见';
 
   COMMENT ON COLUMN "DEV"."P_INFO"."LEAD_S_VIEW" IS '第二审核人意见';
 
   COMMENT ON COLUMN "DEV"."P_INFO"."LEAD_T_VIEW" IS '第三审核人意见';
   
   COMMENT ON COLUMN "DEV"."P_INFO"."APPLY_NAME" IS '申请人';
   
   COMMENT ON COLUMN "DEV"."P_INFO"."APPLY_time" IS '申请时间';
